# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170607_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request_board',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='question_board',
            new_name='Request',
        ),
    ]
