# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170607_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='request',
            name='author',
        ),
    ]
