# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='font_file',
            field=models.CharField(max_length=100),
        ),
    ]
